# Generated by Django 6.0.5 on 2026-05-26 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_add_last_birthday_message_sent_year"),
        ("pos", "0005_add_applied_promotions_to_sale"),
        ("tenants", "0002_add_billing_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebstoreBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("announcement_bar", "Announcement Bar"),
                            ("hero_banner", "Hero Banner"),
                            ("featured_collection", "Featured Collection"),
                            ("image_with_text", "Image with Text"),
                            ("rich_text", "Rich Text"),
                            ("testimonials", "Testimonials"),
                            ("newsletter_signup", "Newsletter Signup"),
                            ("collection_list", "Collection List"),
                            ("slideshow", "Slideshow"),
                            ("video", "Video"),
                            ("countdown_timer", "Countdown Timer"),
                            ("custom_html", "Custom HTML"),
                            ("product_detail", "Product Detail (Main)"),
                            ("product_recommendations", "Product Recommendations"),
                            ("product_reviews", "Product Reviews"),
                            ("collection_header", "Collection Header"),
                            ("product_grid", "Product Grid"),
                            ("collection_filters", "Collection Filters"),
                            ("cart_items", "Cart Items"),
                            ("cart_summary", "Cart Summary"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("schema", models.JSONField(default=list)),
                ("nested_blocks_schema", models.JSONField(default=list)),
                ("react_component_key", models.CharField(max_length=100)),
                ("preview_image_url", models.URLField(blank=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "webstore_block",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebstoreTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("FASHION", "Fashion & Apparel"),
                            ("FOOD", "Food & Beverage"),
                            ("ELECTRONICS", "Electronics"),
                            ("BEAUTY", "Beauty & Health"),
                            ("FURNITURE", "Furniture & Home"),
                            ("JEWELLERY", "Jewellery"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("preview_image_url", models.URLField(blank=True)),
                ("preview_images", models.JSONField(default=list)),
                ("author", models.CharField(default="LankaCommerce", max_length=100)),
                ("is_free", models.BooleanField(default=True)),
                ("price_lkr", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_published", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("default_config", models.JSONField(default=dict)),
                ("supported_sections", models.JSONField(default=list)),
                ("global_settings_schema", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "webstore_theme",
                "ordering": ["-is_default", "-is_free", "name"],
            },
        ),
        migrations.CreateModel(
            name="TenantWebstore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_password_protected", models.BooleanField(default=False)),
                ("store_password_hash", models.CharField(blank=True, max_length=128)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("social_image_url", models.URLField(blank=True)),
                (
                    "storefront_domain",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
                ("cart_settings", models.JSONField(default=dict)),
                (
                    "customer_accounts",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_tenant_webstore",
            },
        ),
        migrations.CreateModel(
            name="WebstoreCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("password_hash", models.CharField(max_length=128)),
                ("addresses", models.JSONField(default=list)),
                ("default_address_id", models.CharField(blank=True, max_length=36)),
                ("accepts_marketing", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webstore_account",
                        to="crm.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore_customers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_customer",
                "unique_together": {("tenant", "email")},
            },
        ),
        migrations.CreateModel(
            name="TenantThemeConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active (Live)"), ("DRAFT", "Draft (Being Edited)")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("purchased_blocks", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_configs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_configs",
                        to="webstore.webstoretheme",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_tenant_theme_config",
            },
        ),
        migrations.CreateModel(
            name="WebstoreCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("handle", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                (
                    "collection_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automated", "Automated")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("filter_rules", models.JSONField(default=list)),
                (
                    "filter_conjunction",
                    models.CharField(
                        choices=[("AND", "All conditions"), ("OR", "Any condition")],
                        default="AND",
                        max_length=3,
                    ),
                ),
                ("manual_product_ids", models.JSONField(default=list)),
                (
                    "sort_order_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manually"),
                            ("best_selling", "Best Selling"),
                            ("alpha_asc", "A–Z"),
                            ("alpha_desc", "Z–A"),
                            ("price_asc", "Price: Low to High"),
                            ("price_desc", "Price: High to Low"),
                            ("newest", "Newest"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore_collections",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_collection",
                "unique_together": {("tenant", "handle")},
            },
        ),
        migrations.CreateModel(
            name="WebstoreMenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("handle", models.SlugField(max_length=100)),
                ("items", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore_menus",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_menu",
                "unique_together": {("tenant", "handle")},
            },
        ),
        migrations.CreateModel(
            name="WebstoreOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order_number", models.CharField(max_length=20)),
                ("customer_email", models.EmailField(max_length=254)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="LKR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("refunded", "Refunded")],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("unfulfilled", "Unfulfilled"),
                            ("partial", "Partial"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="unfulfilled",
                        max_length=20,
                    ),
                ),
                ("line_items", models.JSONField(default=list)),
                ("shipping_address", models.JSONField(default=dict)),
                ("billing_address", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                ("discount_code", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("payment_gateway", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="webstore.webstorecustomer",
                    ),
                ),
                (
                    "pos_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webstore_order",
                        to="pos.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore_orders",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_order",
                "unique_together": {("tenant", "order_number")},
            },
        ),
        migrations.CreateModel(
            name="WebstorePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("handle", models.SlugField(max_length=255)),
                ("body_html", models.TextField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore_pages",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_page",
                "unique_together": {("tenant", "handle")},
            },
        ),
    ]
