# Generated by Django 6.0.5 on 2026-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webstoreorder",
            name="tracking_carrier",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="webstoreorder",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tenantthemeconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active (Live)"),
                    ("DRAFT", "Draft (Being Edited)"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="webstoreorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("partially_paid", "Partially Paid"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
