# Generated by Django 6.0.5 on 2026-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webstore", "0003_payhere_and_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="webstoretheme",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tenantwebstore",
            name="shipping_methods",
            field=models.JSONField(default=list),
        ),
    ]
