# Generated by Django 6.0.5 on 2026-05-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webstore", "0004_add_version_number_to_webstore_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webstoreblock",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
