# Generated by Django 6.0.5 on 2026-05-27 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_add_pos_models"),
        ("tenants", "0002_add_billing_models"),
        ("webstore", "0005_change_webstore_block_is_published_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebstoreAnalyticsEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(default="pageview", max_length=20)),
                ("page_type", models.CharField(max_length=50)),
                ("page_handle", models.CharField(blank=True, max_length=200)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_analytics_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "event_type", "-created_at"],
                        name="webstore_an_tenant__4b03d3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "page_type", "-created_at"],
                        name="webstore_an_tenant__a41a87_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebstoreBlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("handle", models.SlugField(max_length=255)),
                ("author_name", models.CharField(max_length=100)),
                ("body_html", models.TextField()),
                ("excerpt", models.TextField(blank=True, max_length=500)),
                ("featured_image_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("seo_title", models.CharField(blank=True, max_length=60)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_blog_post",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_published", "-published_at"],
                        name="webstore_bl_tenant__a326a6_idx",
                    )
                ],
                "unique_together": {("tenant", "handle")},
            },
        ),
        migrations.CreateModel(
            name="WebstoreProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                ("reviewer_email", models.EmailField(max_length=254)),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="webstore.webstorecustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webstore_reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webstore_product_review",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_approved", "-created_at"],
                        name="webstore_pr_product_b2ad5c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_approved"], name="webstore_pr_tenant__de908c_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="webstore_review_rating_range",
                    )
                ],
            },
        ),
    ]
