# Generated by Django 6.0.5 on 2026-05-21 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pos", "0005_add_applied_promotions_to_sale"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("total_earned", models.DecimalField(decimal_places=2, max_digits=14)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_payouts",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of the user's commission rate at the time this record was created.",
                        max_digits=5,
                    ),
                ),
                (
                    "earned_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="May be negative for returns.", max_digits=14
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission_payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="hr.commissionpayout",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_record",
                        to="pos.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_records",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeClock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("clocked_in_at", models.DateTimeField()),
                ("clocked_out_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_clocks",
                        to="pos.shift",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_clocks",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_clocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-clocked_in_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commissionpayout",
            index=models.Index(fields=["tenant", "user"], name="hr_commissi_tenant__fc9343_idx"),
        ),
        migrations.AddIndex(
            model_name="commissionrecord",
            index=models.Index(fields=["tenant", "user"], name="hr_commissi_tenant__137efe_idx"),
        ),
        migrations.AddIndex(
            model_name="commissionrecord",
            index=models.Index(fields=["sale"], name="hr_commissi_sale_id_9984bf_idx"),
        ),
        migrations.AddIndex(
            model_name="timeclock",
            index=models.Index(fields=["tenant", "user"], name="hr_timecloc_tenant__1c32c2_idx"),
        ),
        migrations.AddIndex(
            model_name="timeclock",
            index=models.Index(fields=["shift"], name="hr_timecloc_shift_i_5daea2_idx"),
        ),
    ]
