# Generated by Django 6.0.5 on 2026-05-21 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_add_commission_timeclock_models"),
        ("pos", "0005_add_applied_promotions_to_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionrecord",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_records",
                to="pos.sale",
            ),
        ),
    ]
