"""
Pure formatting utility for WhatsApp purchase order messages.
No database calls — receives a fully-prefetched PO object.
"""


def format_po_for_whatsapp(po) -> str:
    """Format a purchase order as a WhatsApp text message."""
    lines = [
        po.tenant.name.upper(),
        "-" * 30,
        f"PURCHASE ORDER {str(po.id)[-8:].upper()}",
        f"Supplier: {po.supplier.name}",
        f"Expected Delivery: {po.expected_delivery_date.strftime('%d/%m/%Y') if po.expected_delivery_date else 'Not specified'}",
        "-" * 30,
    ]

    for i, line in enumerate(po.lines.all(), start=1):
        lines.append(
            f"{i}. {line.product_name_snapshot} - {line.variant_description_snapshot} "
            f"| Qty: {line.ordered_qty} | Cost: Rs. {line.expected_cost_price}"
        )

    lines += [
        "-" * 30,
        f"TOTAL: Rs. {po.total_amount}",
        "This order was generated by LankaCommerce. Please confirm receipt by replying to this message.",
    ]

    return "\n".join(lines)
