# Generated by Django 6.0.5 on 2026-05-21 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_add_billing_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("annual_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_users", models.IntegerField()),
                ("max_product_variants", models.IntegerField()),
                ("features", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "billing_subscription_plan",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "payhere_subscription_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_subscriptions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "billing_subscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("VOIDED", "Voided"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("billing_period_start", models.DateTimeField()),
                ("billing_period_end", models.DateTimeField()),
                ("due_date", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payhere_order_id", models.CharField(blank=True, max_length=255, null=True)),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_invoices",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "billing_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("payhere_status_code", models.CharField(max_length=10)),
                ("payhere_order_id", models.CharField(max_length=255)),
                ("payhere_amount", models.CharField(max_length=50)),
                ("payhere_currency", models.CharField(default="LKR", max_length=10)),
                ("payhere_md5sig", models.CharField(max_length=255)),
                ("signature_valid", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_events",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Payment Event",
                "verbose_name_plural": "Invoice Payment Events",
                "db_table": "billing_invoice_payment_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["payhere_order_id"], name="idx_billing_pay_evt_order")
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("THREE_DAY_REMINDER", "3-Day Before"),
                            ("DUE_DATE_REMINDER", "Due Date"),
                            ("OVERDUE_REMINDER", "Overdue"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("WHATSAPP", "WhatsApp"), ("EMAIL", "Email")], max_length=20
                    ),
                ),
                (
                    "send_status",
                    models.CharField(
                        choices=[("SENT", "Sent"), ("FAILED", "Failed")],
                        default="SENT",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_reminders",
                        to="billing.invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_reminders",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Reminder",
                "verbose_name_plural": "Payment Reminders",
                "db_table": "billing_payment_reminder",
                "ordering": ["-sent_at"],
                "indexes": [models.Index(fields=["sent_at"], name="idx_billing_reminder_sent_at")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invoice", "reminder_type", "channel"),
                        name="uniq_billing_reminder_invoice_type_channel",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["subscription", "status"], name="idx_billing_inv_sub_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["tenant", "status"], name="idx_billing_inv_tenant_status"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["due_date"], name="idx_billing_inv_due_date"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["tenant", "status"], name="idx_billing_sub_tenant_status"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["current_period_end"], name="idx_billing_sub_period_end"),
        ),
    ]
