# Generated by Django 6.0.5 on 2026-05-27 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_add_billing_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_annual_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_monthly_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="StripePaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("stripe_session_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("currency", models.CharField(default="LKR", max_length=10)),
                ("processed", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_payment_events",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Payment Event",
                "verbose_name_plural": "Stripe Payment Events",
                "db_table": "billing_stripe_payment_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["stripe_session_id"], name="idx_billing_stripe_session"),
                    models.Index(
                        fields=["invoice", "processed"], name="idx_billing_stripe_inv_proc"
                    ),
                ],
            },
        ),
    ]
