# Generated by Django 6.0.5 on 2026-05-18 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_add_category_and_brand_models"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MEN", "Men"),
                            ("WOMEN", "Women"),
                            ("UNISEX", "Unisex"),
                            ("KIDS", "Kids"),
                            ("OTHER", "Other"),
                        ],
                        default="UNISEX",
                        max_length=10,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "tax_rule",
                    models.CharField(
                        choices=[
                            ("STANDARD_VAT", "Standard VAT"),
                            ("REDUCED_VAT", "Reduced VAT"),
                            ("ZERO_RATED", "Zero Rated"),
                            ("EXEMPT", "Exempt"),
                        ],
                        default="STANDARD_VAT",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "indexes": [
                    models.Index(
                        fields=["tenant", "category"], name="catalog_pro_tenant__48a14c_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_archived"], name="catalog_pro_tenant__666674_idx"
                    ),
                    models.Index(fields=["tenant", "name"], name="catalog_pro_tenant__750d04_idx"),
                ],
            },
        ),
    ]
