# Generated by Django 6.0.5 on 2026-05-18 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_add_product_model"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("colour", models.CharField(blank=True, max_length=100, null=True)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("retail_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "wholesale_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=5)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variants",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "indexes": [
                    models.Index(
                        fields=["tenant", "barcode"], name="catalog_pro_tenant__7b383f_idx"
                    ),
                    models.Index(fields=["tenant", "sku"], name="catalog_pro_tenant__2c5f77_idx"),
                    models.Index(fields=["product"], name="catalog_pro_product_460665_idx"),
                ],
                "unique_together": {("tenant", "barcode"), ("tenant", "sku")},
            },
        ),
    ]
