# Generated by Django 6.0.5 on 2026-05-18 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_product_variant_model"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("SALE_RETURN", "Sale Return"),
                            ("PURCHASE_RECEIPT", "Purchase Receipt"),
                            ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                            ("STOCK_TAKE_ADJUSTMENT", "Stock Take Adjustment"),
                            ("DAMAGE_WRITE_OFF", "Damage Write-Off"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("INITIAL_STOCK", "Initial Stock"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("quantity_before", models.IntegerField()),
                ("quantity_after", models.IntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("sale_id", models.UUIDField(blank=True, null=True)),
                ("purchase_order_id", models.UUIDField(blank=True, null=True)),
                ("stock_take_session_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "created_at"], name="catalog_sto_variant_a29d68_idx"
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="catalog_sto_tenant__62a478_idx"
                    ),
                    models.Index(fields=["actor"], name="catalog_sto_actor_i_9b521b_idx"),
                ],
            },
        ),
    ]
