# Generated by Django 6.0.5 on 2026-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_add_stock_take_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SALE", "Sale"),
                    ("VOID_REVERSAL", "Void Reversal"),
                    ("SALE_RETURN", "Sale Return"),
                    ("PURCHASE_RECEIPT", "Purchase Receipt"),
                    ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                    ("STOCK_TAKE_ADJUSTMENT", "Stock Take Adjustment"),
                    ("DAMAGE_WRITE_OFF", "Damage Write-Off"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("INITIAL_STOCK", "Initial Stock"),
                ],
                max_length=30,
            ),
        ),
    ]
