# Generated by Django 6.0.5 on 2026-05-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_add_promotion_pricing_rule_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
