# Generated by Django 6.0.5 on 2026-05-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_add_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of times this promotion can be used. Null = unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this promotion has been successfully used."
            ),
        ),
    ]
