# Generated by Django 6.0.5 on 2026-05-18 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant context in which the action occurred.",
                        null=True,
                    ),
                ),
                (
                    "actor_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who performed the action.",
                        null=True,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        help_text="Role of the actor at the time of the action.",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity affected, e.g. 'User', 'Product', 'Sale'.",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        blank=True, help_text="UUID of the specific entity affected.", null=True
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed, e.g. 'LOGIN_SUCCESS', 'LOGOUT', 'PIN_LOGIN_FAILED'.",
                        max_length=100,
                    ),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        help_text="State of the entity before the action (for update/delete operations).",
                        null=True,
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        help_text="State of the entity after the action (for create/update operations).",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client that performed the action.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="User-Agent header from the request."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this audit record was created."
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "accounts_auditlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor_id"], name="idx_audit_actor"),
                    models.Index(fields=["tenant_id"], name="idx_audit_tenant"),
                    models.Index(fields=["entity_type", "entity_id"], name="idx_audit_entity"),
                    models.Index(fields=["created_at"], name="idx_audit_created_at"),
                    models.Index(fields=["action"], name="idx_audit_action"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique user identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User's email address. Used as the login identifier.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="The tenant this user belongs to. Null for SUPER_ADMIN.",
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("CASHIER", "Cashier"),
                            ("STOCK_CLERK", "Stock Clerk"),
                        ],
                        default="CASHIER",
                        help_text="Primary role determining access level.",
                        max_length=20,
                    ),
                ),
                (
                    "permissions_list",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Explicit list of permission strings granted to this user. Stored as a JSON array, e.g. ['products.view', 'sales.create'].",
                    ),
                ),
                (
                    "pin_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed PIN for quick login. Empty if PIN is not set.",
                        max_length=128,
                    ),
                ),
                (
                    "session_version",
                    models.IntegerField(
                        default=1,
                        help_text="Monotonically incremented on forced logout. Embedded in JWT; increment invalidates all outstanding tokens.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Designates whether this user account is active."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the Django admin site.",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent successful login.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp. Non-null means the user is deactivated.",
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "accounts_user",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="idx_user_email"),
                    models.Index(fields=["tenant_id"], name="idx_user_tenant"),
                    models.Index(fields=["role"], name="idx_user_role"),
                ],
            },
        ),
    ]
