# Generated by Django 6.0.5 on 2026-05-18 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Cryptographically random token (64 hex characters = 32 bytes of entropy).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Token is invalid after this timestamp."),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="True if this token has already been consumed."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this reset token belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "accounts_passwordresettoken",
                "ordering": ["-created_at"],
            },
        ),
    ]
