# Generated by Django 6.0.5 on 2026-05-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_password_reset_token"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="idx_user_tenant",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tenant_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The tenant this user belongs to. Null for SUPER_ADMIN.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["tenant"], name="idx_user_tenant"),
        ),
    ]
