# Generated by Django 6.0.5 on 2026-05-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_idx_user_tenant_customuser_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="clocked_in_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Denormalised mirror of the latest TimeClock.clocked_in_at. Non-null means the user is currently clocked in. Must be updated atomically with the TimeClock record.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage commission rate applied to completed sales for this staff member.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
