# Generated by Django 6.0.5 on 2026-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_add_customer_supplier_purchase_order_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_birthday_message_sent_year",
            field=models.IntegerField(
                blank=True,
                help_text="The calendar year in which a birthday WhatsApp message was last sent to this customer.",
                null=True,
            ),
        ),
    ]
