# Generated by Django 6.0.5 on 2026-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("SUSPENDED", "Suspended"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="TRIAL",
                max_length=20,
            ),
        ),
    ]
