# Generated by Django 6.0.5 on 2026-05-21 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_add_saved_report_model"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummaryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "Sent"), ("FAILED", "Failed")], max_length=10
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summary_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Summary Log",
                "verbose_name_plural": "Daily Summary Logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
