# Generated by Django 6.0.5 on 2026-05-18 16:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0006_add_pos_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opening_float", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(max_length=50)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "change_given",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("CASH", "Cash"), ("CARD", "Card"), ("SPLIT", "Split")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("COMPLETED", "Completed"),
                            ("VOIDED", "Voided"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("whatsapp_receipt_sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorizing_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="pos.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftClosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("closing_cash_count", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expected_cash", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cash_difference", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_sales_count", models.IntegerField()),
                ("total_sales_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_returns_count", models.IntegerField(default=0)),
                (
                    "total_returns_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("total_cash_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_card_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closure",
                        to="pos.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name_snapshot", models.CharField(max_length=255)),
                ("variant_description_snapshot", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "line_total_before_discount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("line_total_after_discount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.sale",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sale"], name="pos_salelin_sale_id_553468_idx"),
                    models.Index(fields=["variant"], name="pos_salelin_variant_d83366_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["tenant_id", "status"], name="pos_shift_tenant__0f7372_idx"),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["cashier", "status"], name="pos_shift_cashier_e0fa55_idx"),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["tenant_id", "opened_at"], name="pos_shift_tenant__a80d8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["tenant_id", "status", "created_at"], name="pos_sale_tenant__0c76c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["shift"], name="pos_sale_shift_i_0292b4_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["cashier"], name="pos_sale_cashier_a8c41e_idx"),
        ),
    ]
