# Generated by Django 6.0.5 on 2026-05-19 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_add_pos_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(choices=[("CASH", "Cash"), ("CARD", "Card")], max_length=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("card_reference_number", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="pos.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["sale"], name="pos_payment_sale_id_2f56a2_idx")],
            },
        ),
    ]
