# Generated by Django 6.0.5 on 2026-05-19 16:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_add_pos_models"),
        ("pos", "0002_add_payment_model"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD_REVERSAL", "Card Reversal"),
                            ("STORE_CREDIT", "Store Credit"),
                            ("EXCHANGE", "Exchange"),
                        ],
                        max_length=20,
                    ),
                ),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("restock_items", models.BooleanField(default=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed")], default="COMPLETED", max_length=20
                    ),
                ),
                (
                    "card_reversal_reference",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="pos.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="linked_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_sales",
                to="pos.return",
            ),
        ),
        migrations.CreateModel(
            name="ReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name_snapshot", models.CharField(max_length=255)),
                ("variant_description_snapshot", models.CharField(blank=True, max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_refund_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_restocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="pos.saleline",
                    ),
                ),
                (
                    "return_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pos.return",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("customer_id_ref", models.UUIDField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "used_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_credits",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                fields=["tenant", "created_at"], name="pos_return_tenant__65a228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["original_sale"], name="pos_return_origina_6bb03d_idx"),
        ),
        migrations.AddIndex(
            model_name="returnline",
            index=models.Index(fields=["return_record"], name="pos_returnl_return__c3f00f_idx"),
        ),
    ]
