# Generated by Django 6.0.5 on 2026-05-20 02:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_add_customer_supplier_purchase_order_models"),
        ("pos", "0003_add_return_and_storecredit_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="applied_store_credit",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="crm.customer",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_as_salesperson",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("SPLIT", "Split"),
                    ("EXCHANGE", "Exchange"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
