# Generated by Django 6.0.5 on 2026-05-21 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_add_customer_link_to_sale"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="applied_promotions",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot list of promotion rules applied to this sale.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OPENING_FLOAT", "Opening Float"),
                            ("PETTY_CASH_OUT", "Petty Cash Out"),
                            ("MANUAL_IN", "Manual In"),
                            ("MANUAL_OUT", "Manual Out"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Always stored as a positive value.",
                        max_digits=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_cash_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_movements",
                        to="pos.shift",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_movements",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "shift"], name="pos_cashmov_tenant__d470ae_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("SALARIES", "Salaries"),
                            ("UTILITIES", "Utilities"),
                            ("ADVERTISING", "Advertising"),
                            ("MAINTENANCE", "Maintenance"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Always stored as a positive value.",
                        max_digits=12,
                    ),
                ),
                ("description", models.TextField()),
                ("receipt_image_url", models.URLField(blank=True, null=True)),
                ("expense_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "expense_date"], name="pos_expense_tenant__5e905a_idx"
                    )
                ],
            },
        ),
    ]
